import NavBar from "@/components/day-6/navBar";
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// day-6 layout interface
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        {/* navbar can be passed here */}
        {/* <NavBar /> */}

        {/* NAVBAR visible on all pages */}
        <nav className="w-full bg-blue-600 text-white px-6 py-4 flex gap-6">
          {/* Each Link navigates to a different page */}
          <Link href="/" className="hover:underline">
            Home
          </Link>
          <Link href="/about" className="hover:underline">
            About
          </Link>
          <Link href="/contact" className="hover:underline">
            Contact
          </Link>
        </nav>

        {/* children = the actual page content */}
        {children}
      </body>
    </html>
  );
}
